[info]
name = "ALA"
standard_name = "ALA"
charge = 0

[[atoms]]
name = "N"
element = "N"
pos = [-0.966, 0.493, 1.500]

[[atoms]]
name = "CA"
element = "C"
pos = [0.257, 0.418, 0.692]

[[atoms]]
name = "C"
element = "C"
pos = [-0.094, 0.017, -0.716]

[[atoms]]
name = "O"
element = "O"
pos = [-1.056, -0.682, -0.923]

[[atoms]]
name = "CB"
element = "C"
pos = [1.204, -0.620, 1.296]

[[hydrogens]]
name = "H"
pos = [-1.383, -0.425, 1.482]
anchors = ["N", "CA", "C"]

[[hydrogens]]
name = "HA"
pos = [0.746, 1.392, 0.682]
anchors = ["CA", "N", "C"]

[[hydrogens]]
name = "HB1"
pos = [1.459, -0.330, 2.316]
anchors = ["CB", "CA", "N"]

[[hydrogens]]
name = "HB2"
pos = [0.715, -1.594, 1.307]
anchors = ["CB", "CA", "N"]

[[hydrogens]]
name = "HB3"
pos = [2.113, -0.676, 0.697]
anchors = ["CB", "CA", "N"]

[[bonds]]
a1 = "N"
a2 = "CA"
order = "Single"

[[bonds]]
a1 = "N"
a2 = "H"
order = "Single"

[[bonds]]
a1 = "CA"
a2 = "C"
order = "Single"

[[bonds]]
a1 = "CA"
a2 = "CB"
order = "Single"

[[bonds]]
a1 = "CA"
a2 = "HA"
order = "Single"

[[bonds]]
a1 = "C"
a2 = "O"
order = "Double"

[[bonds]]
a1 = "CB"
a2 = "HB1"
order = "Single"

[[bonds]]
a1 = "CB"
a2 = "HB2"
order = "Single"

[[bonds]]
a1 = "CB"
a2 = "HB3"
order = "Single"
