[info]
name = "MET"
standard_name = "MET"
charge = 0

[[atoms]]
name = "N"
element = "N"
pos = [-1.816, 0.142, -1.166]

[[atoms]]
name = "CA"
element = "C"
pos = [-0.392, 0.499, -1.214]

[[atoms]]
name = "C"
element = "C"
pos = [0.206, 0.002, -2.504]

[[atoms]]
name = "O"
element = "O"
pos = [-0.236, -0.989, -3.033]

[[atoms]]
name = "CB"
element = "C"
pos = [0.334, -0.145, -0.032]

[[atoms]]
name = "CG"
element = "C"
pos = [-0.273, 0.359, 1.277]

[[atoms]]
name = "SD"
element = "S"
pos = [0.589, -0.405, 2.678]

[[atoms]]
name = "CE"
element = "C"
pos = [-0.314, 0.353, 4.056]

[[hydrogens]]
name = "H"
pos = [-1.865, -0.864, -1.220]
anchors = ["N", "CA", "C"]

[[hydrogens]]
name = "HA"
pos = [-0.287, 1.582, -1.158]
anchors = ["CA", "N", "CB"]

[[hydrogens]]
name = "HB2"
pos = [1.391, 0.119, -0.068]
anchors = ["CB", "CA", "CG"]

[[hydrogens]]
name = "HB3"
pos = [0.229, -1.229, -0.088]
anchors = ["CB", "CA", "CG"]

[[hydrogens]]
name = "HG2"
pos = [-1.330, 0.094, 1.313]
anchors = ["CG", "CB", "SD"]

[[hydrogens]]
name = "HG3"
pos = [-0.168, 1.442, 1.333]
anchors = ["CG", "CB", "SD"]

[[hydrogens]]
name = "HE1"
pos = [0.090, -0.010, 5.000]
anchors = ["CE", "SD", "CG"]

[[hydrogens]]
name = "HE2"
pos = [-0.207, 1.436, 4.008]
anchors = ["CE", "SD", "CG"]

[[hydrogens]]
name = "HE3"
pos = [-1.369, 0.088, 3.988]
anchors = ["CE", "SD", "CG"]

[[bonds]]
a1 = "N"
a2 = "CA"
order = "Single"

[[bonds]]
a1 = "N"
a2 = "H"
order = "Single"

[[bonds]]
a1 = "CA"
a2 = "C"
order = "Single"

[[bonds]]
a1 = "CA"
a2 = "CB"
order = "Single"

[[bonds]]
a1 = "CA"
a2 = "HA"
order = "Single"

[[bonds]]
a1 = "C"
a2 = "O"
order = "Double"

[[bonds]]
a1 = "CB"
a2 = "CG"
order = "Single"

[[bonds]]
a1 = "CB"
a2 = "HB2"
order = "Single"

[[bonds]]
a1 = "CB"
a2 = "HB3"
order = "Single"

[[bonds]]
a1 = "CG"
a2 = "SD"
order = "Single"

[[bonds]]
a1 = "CG"
a2 = "HG2"
order = "Single"

[[bonds]]
a1 = "CG"
a2 = "HG3"
order = "Single"

[[bonds]]
a1 = "SD"
a2 = "CE"
order = "Single"

[[bonds]]
a1 = "CE"
a2 = "HE1"
order = "Single"

[[bonds]]
a1 = "CE"
a2 = "HE2"
order = "Single"

[[bonds]]
a1 = "CE"
a2 = "HE3"
order = "Single"
