[info]
name = "A"
standard_name = "A"
charge = -1

[[atoms]]
name = "P"
element = "P"
pos = [1.024, -0.137, -4.723]

[[atoms]]
name = "OP1"
element = "O"
pos = [1.633, 1.190, -4.488]

[[atoms]]
name = "OP2"
element = "O"
pos = [-0.183, 0.005, -5.778]

[[atoms]]
name = "O5'"
element = "O"
pos = [0.456, -0.720, -3.334]

[[atoms]]
name = "C5'"
element = "C"
pos = [-0.520, 0.209, -2.863]

[[atoms]]
name = "C4'"
element = "C"
pos = [-1.101, -0.287, -1.538]

[[atoms]]
name = "O4'"
element = "O"
pos = [-0.064, -0.383, -0.538]

[[atoms]]
name = "C3'"
element = "C"
pos = [-2.105, 0.739, -0.969]

[[atoms]]
name = "O3'"
element = "O"
pos = [-3.445, 0.360, -1.287]

[[atoms]]
name = "C2'"
element = "C"
pos = [-1.874, 0.684, 0.558]

[[atoms]]
name = "O2'"
element = "O"
pos = [-3.065, 0.271, 1.231]

[[atoms]]
name = "C1'"
element = "C"
pos = [-0.755, -0.367, 0.729]

[[atoms]]
name = "N9"
element = "N"
pos = [0.158, 0.029, 1.803]

[[atoms]]
name = "C8"
element = "C"
pos = [1.265, 0.813, 1.672]

[[atoms]]
name = "N7"
element = "N"
pos = [1.843, 0.963, 2.828]

[[atoms]]
name = "C5"
element = "C"
pos = [1.143, 0.292, 3.773]

[[atoms]]
name = "C6"
element = "C"
pos = [1.290, 0.091, 5.156]

[[atoms]]
name = "N6"
element = "N"
pos = [2.344, 0.664, 5.846]

[[atoms]]
name = "N1"
element = "N"
pos = [0.391, -0.656, 5.787]

[[atoms]]
name = "C2"
element = "C"
pos = [-0.617, -1.206, 5.136]

[[atoms]]
name = "N3"
element = "N"
pos = [-0.792, -1.051, 3.841]

[[atoms]]
name = "C4"
element = "C"
pos = [0.056, -0.320, 3.126]

[[hydrogens]]
name = "H5'"
pos = [-1.319, 0.301, -3.599]
anchors = ["C5'", "C4'", "O5'"]

[[hydrogens]]
name = "H5''"
pos = [-0.052, 1.182, -2.712]
anchors = ["C5'", "C4'", "O5'"]

[[hydrogens]]
name = "H4'"
pos = [-1.586, -1.254, -1.677]
anchors = ["C4'", "C5'", "C3'"]

[[hydrogens]]
name = "H3'"
pos = [-1.890, 1.736, -1.353]
anchors = ["C3'", "C4'", "C2'"]

[[hydrogens]]
name = "H2'"
pos = [-1.543, 1.654, 0.930]
anchors = ["C2'", "C1'", "C3'"]

[[hydrogens]]
name = "HO2'"
pos = [-3.740, 0.936, 1.037]
anchors = ["O2'", "C2'", "C1'"]

[[hydrogens]]
name = "H1'"
pos = [-1.185, -1.346, 0.940]
anchors = ["C1'", "N9", "C2'"]

[[hydrogens]]
name = "H8"
pos = [1.611, 1.246, 0.745]
anchors = ["C8", "N7", "N9"]

[[hydrogens]]
name = "H61"
pos = [2.432, 0.522, 6.801]
anchors = ["N6", "C6", "C5"]

[[hydrogens]]
name = "H62"
pos = [2.996, 1.205, 5.374]
anchors = ["N6", "C6", "C5"]

[[hydrogens]]
name = "H2"
pos = [-1.325, -1.807, 5.688]
anchors = ["C2", "N1", "N3"]

[[bonds]]
a1 = "P"
a2 = "OP1"
order = "Double"

[[bonds]]
a1 = "P"
a2 = "OP2"
order = "Single"

[[bonds]]
a1 = "P"
a2 = "O5'"
order = "Single"

[[bonds]]
a1 = "O5'"
a2 = "C5'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "C4'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "H5'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "H5''"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "O4'"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "C3'"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "H4'"
order = "Single"

[[bonds]]
a1 = "O4'"
a2 = "C1'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "O3'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "C2'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "H3'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "O2'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "C1'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "H2'"
order = "Single"

[[bonds]]
a1 = "O2'"
a2 = "HO2'"
order = "Single"

[[bonds]]
a1 = "C1'"
a2 = "N9"
order = "Single"

[[bonds]]
a1 = "C1'"
a2 = "H1'"
order = "Single"

[[bonds]]
a1 = "N9"
a2 = "C8"
order = "Aromatic"

[[bonds]]
a1 = "N9"
a2 = "C4"
order = "Aromatic"

[[bonds]]
a1 = "C8"
a2 = "N7"
order = "Aromatic"

[[bonds]]
a1 = "C8"
a2 = "H8"
order = "Single"

[[bonds]]
a1 = "N7"
a2 = "C5"
order = "Aromatic"

[[bonds]]
a1 = "C5"
a2 = "C6"
order = "Aromatic"

[[bonds]]
a1 = "C5"
a2 = "C4"
order = "Aromatic"

[[bonds]]
a1 = "C6"
a2 = "N6"
order = "Single"

[[bonds]]
a1 = "C6"
a2 = "N1"
order = "Aromatic"

[[bonds]]
a1 = "N6"
a2 = "H61"
order = "Single"

[[bonds]]
a1 = "N6"
a2 = "H62"
order = "Single"

[[bonds]]
a1 = "N1"
a2 = "C2"
order = "Aromatic"

[[bonds]]
a1 = "C2"
a2 = "N3"
order = "Aromatic"

[[bonds]]
a1 = "C2"
a2 = "H2"
order = "Single"

[[bonds]]
a1 = "N3"
a2 = "C4"
order = "Aromatic"
