[info]
name = "C"
standard_name = "C"
charge = -1

[[atoms]]
name = "P"
element = "P"
pos = [1.049, -0.039, -4.028]

[[atoms]]
name = "OP1"
element = "O"
pos = [1.692, 1.237, -3.646]

[[atoms]]
name = "OP2"
element = "O"
pos = [-0.116, 0.246, -5.102]

[[atoms]]
name = "O5'"
element = "O"
pos = [0.415, -0.733, -2.721]

[[atoms]]
name = "C5'"
element = "C"
pos = [-0.546, 0.181, -2.193]

[[atoms]]
name = "C4'"
element = "C"
pos = [-1.189, -0.419, -0.942]

[[atoms]]
name = "O4'"
element = "O"
pos = [-0.190, -0.648, 0.076]

[[atoms]]
name = "C3'"
element = "C"
pos = [-2.178, 0.583, -0.307]

[[atoms]]
name = "O3'"
element = "O"
pos = [-3.518, 0.283, -0.703]

[[atoms]]
name = "C2'"
element = "C"
pos = [-2.001, 0.373, 1.215]

[[atoms]]
name = "O2'"
element = "O"
pos = [-3.228, -0.059, 1.806]

[[atoms]]
name = "C1'"
element = "C"
pos = [-0.924, -0.729, 1.317]

[[atoms]]
name = "N1"
element = "N"
pos = [-0.036, -0.470, 2.453]

[[atoms]]
name = "C2"
element = "C"
pos = [0.652, 0.683, 2.514]

[[atoms]]
name = "O2"
element = "O"
pos = [0.529, 1.504, 1.620]

[[atoms]]
name = "N3"
element = "N"
pos = [1.467, 0.945, 3.535]

[[atoms]]
name = "C4"
element = "C"
pos = [1.620, 0.070, 4.520]

[[atoms]]
name = "N4"
element = "N"
pos = [2.464, 0.350, 5.569]

[[atoms]]
name = "C5"
element = "C"
pos = [0.916, -1.151, 4.483]

[[atoms]]
name = "C6"
element = "C"
pos = [0.087, -1.399, 3.442]

[[hydrogens]]
name = "H5'"
pos = [-1.315, 0.371, -2.941]
anchors = ["C5'", "C4'", "O5'"]

[[hydrogens]]
name = "H5''"
pos = [-0.052, 1.118, -1.933]
anchors = ["C5'", "C4'", "O5'"]

[[hydrogens]]
name = "H4'"
pos = [-1.699, -1.350, -1.188]
anchors = ["C4'", "C5'", "C3'"]

[[hydrogens]]
name = "H3'"
pos = [-1.917, 1.604, -0.586]
anchors = ["C3'", "C4'", "C2'"]

[[hydrogens]]
name = "H2'"
pos = [-1.653, 1.290, 1.689]
anchors = ["C2'", "C1'", "C3'"]

[[hydrogens]]
name = "HO2'"
pos = [-3.874, 0.644, 1.656]
anchors = ["O2'", "C2'", "C1'"]

[[hydrogens]]
name = "H1'"
pos = [-1.392, -1.708, 1.418]
anchors = ["C1'", "N1", "C2'"]

[[hydrogens]]
name = "H41"
pos = [2.950, 1.189, 5.590]
anchors = ["N4", "C4", "N3"]

[[hydrogens]]
name = "H42"
pos = [2.571, -0.289, 6.290]
anchors = ["N4", "C4", "N3"]

[[hydrogens]]
name = "H5"
pos = [1.030, -1.873, 5.278]
anchors = ["C5", "C4", "C6"]

[[hydrogens]]
name = "H6"
pos = [-0.465, -2.326, 3.393]
anchors = ["C6", "N1", "C5"]

[[bonds]]
a1 = "P"
a2 = "OP1"
order = "Double"

[[bonds]]
a1 = "P"
a2 = "OP2"
order = "Single"

[[bonds]]
a1 = "P"
a2 = "O5'"
order = "Single"

[[bonds]]
a1 = "O5'"
a2 = "C5'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "C4'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "H5'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "H5''"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "O4'"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "C3'"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "H4'"
order = "Single"

[[bonds]]
a1 = "O4'"
a2 = "C1'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "O3'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "C2'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "H3'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "O2'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "C1'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "H2'"
order = "Single"

[[bonds]]
a1 = "O2'"
a2 = "HO2'"
order = "Single"

[[bonds]]
a1 = "C1'"
a2 = "N1"
order = "Single"

[[bonds]]
a1 = "C1'"
a2 = "H1'"
order = "Single"

[[bonds]]
a1 = "N1"
a2 = "C2"
order = "Single"

[[bonds]]
a1 = "N1"
a2 = "C6"
order = "Single"

[[bonds]]
a1 = "C2"
a2 = "O2"
order = "Double"

[[bonds]]
a1 = "C2"
a2 = "N3"
order = "Single"

[[bonds]]
a1 = "N3"
a2 = "C4"
order = "Double"

[[bonds]]
a1 = "C4"
a2 = "N4"
order = "Single"

[[bonds]]
a1 = "C4"
a2 = "C5"
order = "Single"

[[bonds]]
a1 = "N4"
a2 = "H41"
order = "Single"

[[bonds]]
a1 = "N4"
a2 = "H42"
order = "Single"

[[bonds]]
a1 = "C5"
a2 = "C6"
order = "Double"

[[bonds]]
a1 = "C5"
a2 = "H5"
order = "Single"

[[bonds]]
a1 = "C6"
a2 = "H6"
order = "Single"
