[info]
name = "U"
standard_name = "U"
charge = -1

[[atoms]]
name = "P"
element = "P"
pos = [-1.030, 0.047, -4.037]

[[atoms]]
name = "OP1"
element = "O"
pos = [-1.679, -1.228, -3.660]

[[atoms]]
name = "OP2"
element = "O"
pos = [0.138, -0.241, -5.107]

[[atoms]]
name = "O5'"
element = "O"
pos = [-0.399, 0.736, -2.726]

[[atoms]]
name = "C5'"
element = "C"
pos = [0.557, -0.182, -2.196]

[[atoms]]
name = "C4'"
element = "C"
pos = [1.197, 0.415, -0.942]

[[atoms]]
name = "O4'"
element = "O"
pos = [0.194, 0.645, 0.074]

[[atoms]]
name = "C3'"
element = "C"
pos = [2.181, -0.588, -0.301]

[[atoms]]
name = "O3'"
element = "O"
pos = [3.524, -0.288, -0.686]

[[atoms]]
name = "C2'"
element = "C"
pos = [1.995, -0.383, 1.218]

[[atoms]]
name = "O2'"
element = "O"
pos = [3.219, 0.046, 1.819]

[[atoms]]
name = "C1'"
element = "C"
pos = [0.922, 0.723, 1.319]

[[atoms]]
name = "N1"
element = "N"
pos = [0.028, 0.464, 2.451]

[[atoms]]
name = "C2"
element = "C"
pos = [-0.690, -0.671, 2.486]

[[atoms]]
name = "O2"
element = "O"
pos = [-0.587, -1.474, 1.580]

[[atoms]]
name = "N3"
element = "N"
pos = [-1.515, -0.936, 3.517]

[[atoms]]
name = "C4"
element = "C"
pos = [-1.641, -0.055, 4.530]

[[atoms]]
name = "O4"
element = "O"
pos = [-2.391, -0.292, 5.460]

[[atoms]]
name = "C5"
element = "C"
pos = [-0.894, 1.146, 4.502]

[[atoms]]
name = "C6"
element = "C"
pos = [-0.070, 1.384, 3.459]

[[hydrogens]]
name = "H5'"
pos = [1.329, -0.373, -2.942]
anchors = ["C5'", "C4'", "O5'"]

[[hydrogens]]
name = "H5''"
pos = [0.060, -1.117, -1.940]
anchors = ["C5'", "C4'", "O5'"]

[[hydrogens]]
name = "H4'"
pos = [1.712, 1.345, -1.185]
anchors = ["C4'", "C5'", "C3'"]

[[hydrogens]]
name = "H3'"
pos = [1.923, -1.609, -0.583]
anchors = ["C3'", "C4'", "C2'"]

[[hydrogens]]
name = "H2'"
pos = [1.643, -1.301, 1.688]
anchors = ["C2'", "C1'", "C3'"]

[[hydrogens]]
name = "HO2'"
pos = [3.865, -0.657, 1.671]
anchors = ["O2'", "C2'", "C1'"]

[[hydrogens]]
name = "H1'"
pos = [1.392, 1.700, 1.423]
anchors = ["C1'", "N1", "C2'"]

[[hydrogens]]
name = "H3"
pos = [-2.024, -1.762, 3.528]
anchors = ["N3", "C2", "C4"]

[[hydrogens]]
name = "H5"
pos = [-0.982, 1.863, 5.305]
anchors = ["C5", "C4", "C6"]

[[hydrogens]]
name = "H6"
pos = [0.507, 2.295, 3.421]
anchors = ["C6", "N1", "C5"]

[[bonds]]
a1 = "P"
a2 = "OP1"
order = "Double"

[[bonds]]
a1 = "P"
a2 = "OP2"
order = "Single"

[[bonds]]
a1 = "P"
a2 = "O5'"
order = "Single"

[[bonds]]
a1 = "O5'"
a2 = "C5'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "C4'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "H5'"
order = "Single"

[[bonds]]
a1 = "C5'"
a2 = "H5''"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "O4'"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "C3'"
order = "Single"

[[bonds]]
a1 = "C4'"
a2 = "H4'"
order = "Single"

[[bonds]]
a1 = "O4'"
a2 = "C1'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "O3'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "C2'"
order = "Single"

[[bonds]]
a1 = "C3'"
a2 = "H3'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "O2'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "C1'"
order = "Single"

[[bonds]]
a1 = "C2'"
a2 = "H2'"
order = "Single"

[[bonds]]
a1 = "O2'"
a2 = "HO2'"
order = "Single"

[[bonds]]
a1 = "C1'"
a2 = "N1"
order = "Single"

[[bonds]]
a1 = "C1'"
a2 = "H1'"
order = "Single"

[[bonds]]
a1 = "N1"
a2 = "C2"
order = "Single"

[[bonds]]
a1 = "N1"
a2 = "C6"
order = "Single"

[[bonds]]
a1 = "C2"
a2 = "O2"
order = "Double"

[[bonds]]
a1 = "C2"
a2 = "N3"
order = "Single"

[[bonds]]
a1 = "N3"
a2 = "C4"
order = "Single"

[[bonds]]
a1 = "N3"
a2 = "H3"
order = "Single"

[[bonds]]
a1 = "C4"
a2 = "O4"
order = "Double"

[[bonds]]
a1 = "C4"
a2 = "C5"
order = "Single"

[[bonds]]
a1 = "C5"
a2 = "C6"
order = "Double"

[[bonds]]
a1 = "C5"
a2 = "H5"
order = "Single"

[[bonds]]
a1 = "C6"
a2 = "H6"
order = "Single"
