[info]
name = "CYX"
standard_name = "CYS"
charge = 0
type = "Protein"

[[atoms]]
name = "N"
element = "N"
pos = [1.585, 0.483, -0.081]

[[atoms]]
name = "CA"
element = "C"
pos = [0.141, 0.450, 0.186]

[[atoms]]
name = "C"
element = "C"
pos = [-0.095, 0.006, 1.606]

[[atoms]]
name = "O"
element = "O"
pos = [0.685, -0.742, 2.143]

[[atoms]]
name = "CB"
element = "C"
pos = [-0.533, -0.530, -0.774]

[[atoms]]
name = "SG"
element = "S"
pos = [-0.247, 0.004, -2.484]

[[hydrogens]]
name = "H"
pos = [1.928, -0.454, 0.063]
anchors = ["N", "CA", "C"]

[[hydrogens]]
name = "HA"
pos = [-0.277, 1.446, 0.042]
anchors = ["CA", "N", "C"]

[[hydrogens]]
name = "HB2"
pos = [-0.114, -1.526, -0.630]
anchors = ["CB", "CA", "SG"]

[[hydrogens]]
name = "HB3"
pos = [-1.604, -0.554, -0.575]
anchors = ["CB", "CA", "SG"]

[[bonds]]
a1 = "N"
a2 = "CA"
order = 1.0

[[bonds]]
a1 = "N"
a2 = "H"
order = 1.0

[[bonds]]
a1 = "CA"
a2 = "C"
order = 1.0

[[bonds]]
a1 = "CA"
a2 = "CB"
order = 1.0

[[bonds]]
a1 = "CA"
a2 = "HA"
order = 1.0

[[bonds]]
a1 = "C"
a2 = "O"
order = 2.0

[[bonds]]
a1 = "CB"
a2 = "SG"
order = 1.0

[[bonds]]
a1 = "CB"
a2 = "HB2"
order = 1.0

[[bonds]]
a1 = "CB"
a2 = "HB3"
order = 1.0
