name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  core:
    name: Core (CLI & Lib)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Build Workspace
        run: cargo build --verbose --workspace

      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Run tests
        run: cargo test --verbose --workspace

      - name: Check documentation
        run: cargo doc --workspace --document-private-items

  wasm:
    name: WASM Bindings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Build WASM
        run: wasm-pack build crates/bio-forge-wasm --target bundler

  web:
    name: Web App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build WASM package
        run: npm run wasm
        working-directory: ./web

      - name: Install dependencies
        run: npm install
        working-directory: ./web

      - name: Run type check
        run: npm run type-check
        working-directory: ./web

      - name: Run lint
        run: npm run lint
        working-directory: ./web

      - name: Build web app
        run: npm run build
        working-directory: ./web
